load_module /usr/lib/nginx/modules/ngx_rtmp_module.so;

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 8080;
        server_name _;
        location / { return 200 'streamlive-nginx'; }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        max_message 4M;

        application live {
            live on;
            record off;
            allow publish all;
            deny play all;

            on_publish http://127.0.0.1:5200/api/rtmp/auth;
            on_publish_done http://127.0.0.1:5200/api/rtmp/done;

            hls on;
            hls_path /app/data/hls;
            hls_fragment 2s;
            hls_playlist_length 6s;
            hls_continuous on;
            hls_cleanup on;
            hls_nested on;
        }
    }
}
